Automate 2FA with twilio
untitledstartup/fastlane pull request #5
Opened 2021-06-09 17:02 UTC by cccCody

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

### Description

2021-06-09 20:30 UTC, addbrick requested changes
Looks good just a couple comments.

2021-06-09 20:30 UTC, addbrick commented on spaceship/lib/spaceship/two_step_client.rb
> +          sleep(5)
Because of how many times login is going to be called, I don't think we should sleep for so long or loop for so long. At most I think we should wait 15 seconds for the text message to come through, if it doesn't then throw an error. Or make this settable through an option. With this, it could add another two minutes to an already slow process.

2021-06-09 20:30 UTC, addbrick commented on spaceship/lib/spaceship/two_step_client.rb
> +      puts("Successfully requested text message to #{chosen_phone_number['numberWithDialCode']}")
Can this be encapsulated and shared between the two methods?

2021-06-09 23:11 UTC, timherby approved these changes
LGTM besides the existing comments

2021-06-09 23:13 UTC, vishnun requested changes

2021-06-09 23:13 UTC, vishnun commented on spaceship/lib/spaceship/client.rb
> +    attr_reader :twilio_client
Can be combined

```suggestion
    attr_reader :client, :twilio_client
```

2021-06-09 23:13 UTC, vishnun commented on spaceship/lib/spaceship/two_step_client.rb
> +      target_phone_number_suffix = '29' #@twilio_number[-2..-1]
This needs a comment to explain why it's 29

2021-06-09 23:13 UTC, vishnun commented on spaceship/lib/spaceship/two_step_client.rb
> +      phone_number = phone_numbers.find {|p| p['obfuscatedNumber'].end_with?(target_phone_number_suffix) }
```suggestion
      phone_number = phone_numbers.find { |p| p['obfuscatedNumber'].end_with?(target_phone_number_suffix) }
```

2021-06-09 23:13 UTC, vishnun commented on spaceship/lib/spaceship/two_step_client.rb
> +      15.times do
This could also use a comment or a named constant for the 15

2021-06-09 23:13 UTC, vishnun commented
Forgot to add a comment to the PR. Overall Looks great. Just minor comments to consider

2021-06-09 23:14 UTC, cccCody commented on spaceship/lib/spaceship/two_step_client.rb
> +      target_phone_number_suffix = '29' #@twilio_number[-2..-1]
oops! this is the end of my phone number that i swapped in to test with

2021-06-12 01:58 UTC, vishnun approved these changes
LGTM !! The comment needs to be updated though. Approving in advance.

2021-06-12 01:58 UTC, vishnun commented on spaceship/lib/spaceship/two_step_client.rb
> +      # retry up to 15x with 1s delay
The what can be seen in the code. The comment doesn't answer "Why?"

2021-06-15 21:26 UTC, cccCody commented
closing, replacing with google voice in https://github.com/untitledstartup/fastlane/pull/6

2021-06-15 21:26 UTC, closed without merging