Update IAP automation to support two factor auth with google voice
untitledstartup/fastlane pull request #6
Opened 2021-06-15 01:41 UTC by cccCody

2021-06-15 21:22 UTC, addbrick requested changes
Looks good just a couple of comments

2021-06-15 21:22 UTC, addbrick commented on spaceship/lib/spaceship/two_step_client.rb
> +      sleep(5)
Resharing my comment from the previous PR https://github.com/untitledstartup/fastlane/pull/5#discussion_r648661983. Can this wait be reduced or be passed in as an option

2021-06-15 21:22 UTC, addbrick commented on spaceship/lib/spaceship/two_step_client.rb
> +      imap = Net::IMAP.new("imap.gmail.com", 993, true, nil, false)
Please add a comment explaining the setup and why we have to check gmail

2021-06-15 21:32 UTC, cccCody commented on spaceship/lib/spaceship/two_step_client.rb
> +      sleep(5)
I don't think this can be reduced (by much at least). I noticed it pretty consistently took about 3-3.5 sec. But unlike in the other PR, this isn't done in a loop. I can make it a parameter though

2021-06-16 01:06 UTC, addbrick commented on spaceship/lib/spaceship/two_step_client.rb
> +      sleep(5)
awesome thanks!

2021-06-16 01:07 UTC, addbrick approved these changes
looks good

2021-06-17 00:27 UTC, vishnun approved these changes
LGTM!! Minor suggestions. Approving in advance.

2021-06-17 00:27 UTC, vishnun commented on spaceship/lib/spaceship/client.rb
> +    def self.login(user = nil, password = nil, google_number = nil, google_account = nil, google_password = nil, mail_delay)
Having parameters with default values before the last one which does not is not a pattern we use.
Like the `spaceship.rb` we can add a default value for that as well.

2021-06-17 00:27 UTC, vishnun commented on spaceship/lib/spaceship/client.rb
> +    def login(user = nil, password = nil, google_number = nil, google_account = nil, google_password = nil, mail_delay)
ditto

2021-06-17 00:27 UTC, vishnun commented on spaceship/lib/spaceship/two_step_client.rb
> +      phone_number = phone_numbers.find {|p| p['numberWithDialCode'] == chosen_phone_number}
```suggestion
      phone_number = phone_numbers.find { |phone| phone['numberWithDialCode'] == chosen_phone_number}
```

2021-06-17 20:53 UTC, merged